services:
  - type: web
    name: fastapi-gemini
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HF_API_TOKEN
        sync: false
      - key: QWEN_MODEL
        value: Qwen/Qwen2.5-VL-7B-Instruct
      - key: FLUX_MODEL_ID
        value: black-forest-labs/FLUX.1-dev
